### ISSUE TITLE
Outil de gestion du floor map

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#103]
# Views
- Système CRUD pour les locations
- Fonctionnalité de refresh du floor_plan (pour accélerer la mise a jour en cas de changement)
# Administration
- Mise en place de l'administration django pour la gestion des rooms et des rooms_type

**Comment by RignonNoel** [comment]
Il faut porter une attention toute particulière au fait que seul les personnes du Centech peuvent accéder au détails de CRUD et à sa gestion.

Il faut aussi faire attention a ce que l'interface soit clair et compréhensible par des néophite. Je t'invite donc a faire un peu de réflexion sur ce point avant de commencer a coder. 
- Utilisation des alerts pour retour utilisateur (succés, échec, warning)
- Utilisation des messages d'information pour guider l'utilisateur
- Placement des fonctionnalités et logique d'accès.

Essaye de faire correspondre l'interface avec le reste du site, de manière a garder en continuité et a ne pas dispersé l'utilisateur.

Enfin si tu as des idées intéressante, n'hésite pas a les dire. Peut être qu'une partie des autres interfaces pourrait être retravailler pour correspondre a ta nouvelle qui serait plus pertinente. 

PS: La partie administration ne demande pas beaucoup de temps en interface, je te conseille de laisser celle par défaut pour le moment. Au besoin nous pourrons ouvrir un nouveau ticket pour cela.

**Comment by digzol** [comment]
J'ai deux idées qui me viens à l'esprit pour l'affichage des locations et je n'arrive pas à décider.

## Idée 1

Nouvelle section sous la section mentors suivant le model utilisé par la page de présence. Exemple :

**Historique des locations**

| Local | Date début | Date fin | Modifier | Supprimer |
| --- | --- | --- | --- | --- |
| C-1220 | 2015/06/24 | 2016/06/24 | [Modifier] | [Supprimer] |
| C-1240 | 2015/08/24 | 2016/08/24 | [Modifier] | [Supprimer] |

**[Nouvelle location]**

Note : Il ne risque pas d'avoir beaucoup d'entrées dans cette zone (max 10 pour 2-3 locaux?), mais à toi de voir si tu crois que l'ajout d'un tab serait plus intéressant.
- Advantages : 
  - Historique et création/modification au même endroit
  - Court, facile à lire
  - Simple à coder
- Désavantages : 
  - Section vide pour entreprises qui ne louent pas de locaux
  - Risque de ne pas prendre plus que 1 ou 2 lignes pour la plupart des entreprises
  - Vue d'ensemble sur les locaux difficile
  - Plus de cliques nécessaires pour faire la location de plusieurs entreprises à la fois

## Idée 2

Ajouter une nouvelle page Location dans le menu principal.

Sur cette page, une grille est présente avec chaque locaux ainsi que leurs disponibilité. Exemple: 

**Locaux du Centech**

<table style="text-align:center">
  <tr>
    <th>Local</th>
    <th>Entreprise</th>
    <th>Date début</th>
    <th>Date fin</th>
    <th>Modifier</th>
    <th>Supprimer</th>
  </tr>
  <tr>
    <td>C-1220</td>
    <td>[Centech]</td>
    <td>2015/06/24</td>
    <td>2016/06/24</td>
    <td>[Modifier]</td>
    <td>[Supprimer]</td>
  </tr>
  <tr>
    <td>C-1240</td>
    <td colspan=5> [Ajouter une entreprise]</td>
  </tr>
  <tr>
    <td>C-1250</td>
    <td>[QuickTask]</td>
    <td>2015/06/24</td>
    <td>2016/06/24</td>
    <td>[Modifier]</td>
    <td>[Supprimer]</td>
  </tr>
</table>
- Advantages : 
  - Meilleur vue d'ensemble
  - Gestion de plusieurs entreprises plus facile
  - Facile à voir quels locaux sont libres
  - Plus interactif et agréable d'utilisation (préférence personnel)
- Désavantages : 
  - Beaucoup d'informations
  - Difficile à voir si une entreprise a plusieurs locaux
  - Manque l'historique de l'entreprise. Il y aura quand même un tableau sur la page de l'entreprise mais qui ne permettra pas d'actions.

**Comment by RignonNoel** [comment]
Bien vue. C'est effectivement difficile à choisir.

Ne serait-il pas pertinent de faire un choice en haut de la page pour choisir de trier en mode historique ou en mode salle?

Car on perd des données dans les deux cas ici.

**Comment by digzol** [comment]
Documentation v.1.0:

EDIT : v.1.1 available through google docs
https://docs.google.com/document/d/1D2cmfV1k5KZoZIBrcdr_y0tW-pmzJaLfphEShoZeV-U/edit?usp=sharing

**Comment by RignonNoel** [comment]
Oui c'est pas mal du tout. Par contre je n'ai pas le temps de la lire tout de suite mais je m'en occupe bientôt... 

Bon boulot

Par contre privilégié des photos de schéma manuel tu ira plus vite et je suis capable de les lires.

**Comment by digzol** [comment]
C'est déjà assez rapide en utilisant Lucidchart je crois, en plus, j'ai pas de cell et je ne crois pas que Paint serait une option valide.
