### ISSUE TITLE
Affichage du détail des salles

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#104]
# views
- Ajouter une page ou l'on peut voir
  - La compagnie qui loue
  - Un lien vers cette même compagnie
  - La description de l'entreprise
  - La description de la salle
  - Le code de la salle
  - La surface de la salle

Les questions de prix me semble peu pertinente a cette étape du projet. Il serait plus cohérent d'intégrer ça dans un module ou les entrepreneurs pourrais faire une demande de location.

**Comment by digzol** [comment]
Ajouter un historique des locations seulement visible par le Centech serait aussi une bonne idée je crois. Mais Hélène avoue avoir une préférence pour un historique sur la page de l'entreprise plutôt que sur la page d'un local, par exemple.

EDIT : Voir issue #167

**Comment by RignonNoel** [comment]
C'est vrai que sa vision est peut-être plus pertinente du point de vue de l'utilisateur.

Dans ce cas il serait peut être pertinent de mettre l'information de location sur la page de l'entreprise mais dans un systéme de [tab bootstrap](http://getbootstrap.com/components/#nav-tabs)

**Comment by digzol** [comment]
Related issues :
- Required phone number field (#169)
- Required room size field (#170)

**Comment by RignonNoel** [comment]
Je n'ai pas encore eu ta PR sur cette fonctionnalité, tu as un problème avec?
