### ISSUE TITLE
Standardize to PEP8

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#116]
We need to standadize the project to PEP8.
Add travis test for PEP8

**Comment by RignonNoel** [comment]
- [x] BusinessCanvad
- [x] Company
- [x] Experiment
- [x] Finance
- [x] Founder
- [x] Home
- [x] Kanboard
- [x] Kpi
- [x] Mentor
- [x] ValueProposition

**Comment by digzol** [comment]
Should I go ahead and do issue #123 so then you can run PEP8 through Home app?

**Comment by RignonNoel** [comment]
If you want, yes. I work on other app.
