### ISSUE TITLE
error pep8 on home urls

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#127]
> ./app/home/urls.py:67:5: E265 block comment should start with '# '
> 
> ```
> #),
> ```

Just correct this typo

**Comment by digzol** [comment]
Already fixed. Committed directly onto `dev` because it's such a small issue...

**Comment by RignonNoel** [comment]
no, pr

**Comment by digzol** [comment]
I already committed c1810121cfb021b255b344304636b56bb3b5afc5 seconds before you opened this issue. Can you revert that commit so I can add this space in a PR?

**Comment by RignonNoel** [comment]
You can do this you, you're owner in the project.
Do a git reset and a push --hard

**Comment by RignonNoel** [comment]
A partir de maintenant nous devons utiliser que des PR afin d'accepter des contributions plus simplement et ameliorer la qualite du projet.

**Comment by NicholasSavard** [comment]
J'arrive pas a changer de branche après avoir clone le projet, il me fait toujours un nouvelle branche "dev".
