### ISSUE TITLE
add form to edit room

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#166]

**Comment by digzol** [comment]
To access the form : 
- Add "Edit" button at the top of room details section
- **Access** : Centech-only

Form fields : 
- Change room type (Centech, Rental, Unavailable)
- Code
- Static label
- Default cost
- Room size
- All other options are only available through admin panel as things may break

Summary & validation : 
- Warn user if price is set and type is not rental and make user confirm
- Cost and size are optional
- Show label with cost per size

## Without #104

To access the form : 
- Unaccessible
- **Access** : Centech-only

Form fields : 
- Change room type (Centech, Rental, Unavailable)
- Code
- Static label
- Room size
- All other options are only available through admin panel as things may break

Summary & validation : 
- Size is optional

**Comment by digzol** [comment]
Will need a new PR to fully implement the functionalities from PR #195 and PR #193
