### ISSUE TITLE
add a kanban board (manage task & project)

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#17]
something like this http://kanbantool.com/online-kanban-board
try and find an open source starting point

**Comment by RignonNoel** [comment]
I've found an open starting point: https://github.com/zellyn/django-kanboard
The project is not finalized, and it needed lot of work but it's ok for me. I've already debug and integrated the project in the dashboard.

I need now to know what you want in this functionnality. For example we can:
- Add new phase (but is it very interesting for us ?)
- Add sub-phase
- Add row/colaborators (I think it's important for us)
- Add a system of date for auto-change the phase of a card
- Add system of coloration
- Add an archive system

...

For the moment i have work to:
- Add, Modify and Delete a card
- Change phase and order of a card

I wait your opinion. Have a good week end!
