### ISSUE TITLE
Bug - Responsive pages

### ISSUE THREAD

**Issue by digzol** [CentechMTL/TableauDeBord#180]
As noted previously, right page margin is hidden when in a certain window width range.

This is because the parent `.container` sets the responsive page width. In our case, the `.navbar` is outside `.container`so the page will always be too wide by whatever width `.navbar` has.

Current : 

```
<nav class="navbar navbar-default navbar-fixed-side">
  <!-- normal collapsible navbar markup -->
</nav>
<div id="page-wrapper">
  <div id="top-menu">...</div>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!-- your page content -->
      </div>
    </div>
  </div>
</div>
```

Should be (something like ) : 

```
<div class="container">
  <div class="row">
    <div class="col-lg-2">
      <nav class="navbar navbar-default navbar-fixed-side">
        <!-- normal collapsible navbar markup -->
      </nav>
    </div>
    <div class="col-lg-12">
      <!-- your page content -->
  </div>
</div>
```

**Comment by RignonNoel** [comment]
Oh nice! So we just need to try and PR ;)

**Comment by digzol** [comment]
C'est un peu plus compliqué... le grid system de Bootstrap est vraiment pas fait pour notre theme.
Mais j'ai trouvé un hack plus simple.

La class `.container` utilise un fixed size de 1170px, 970px et 750px puis devient fluide.

Mais si on utilise `.container-fluid` et on limite le `max-width` à 1170px on a le même résultat sur écran large, et les petites écrans auront toujours un contenu fluide au lieu d'être fixé à 970px ou 750px.

**Comment by RignonNoel** [comment]
Le thème est un thème bootstrap normalement.
