### ISSUE TITLE
Mentor subdivisé en 2 types ??

### ISSUE THREAD

**Issue by gillescarrier** [CentechMTL/TableauDeBord#25]
2 types = 
mentor d'affaires
mentor technologiques  ??

**Comment by RignonNoel** [comment]
A discuter avec @appliedrd lors de la prochaine réunion de projet.

**Comment by RignonNoel** [comment]
Les deux types ont été rajouté.
On peut maintenant modifier les mentors et assigner directement les nouveaux.

Un onglet de recherche a été ajouté de manière a les triés plus facilement dans la liste des mentors.
