### ISSUE TITLE
kanboard - mentor assign task to founder or company

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#30]
mentors assign tasks to company. can also  select  specific founder
add title, description, deadline

founders can comment but cannot change due date or title or description
add field comment so founders can add info to the task

**Comment by RignonNoel** [comment]
- Only the creator of the card can modify the card
- The creator can select a founder of the company to assign the task
- Other people can comment the card (the creator too, for discuss about the task)

**Comment by appliedrd** [comment]
I need a test mentor account

**Comment by RignonNoel** [comment]
You can create your mentor account directly by your admin account with the top-right menu. (on the test server)

**Comment by appliedrd** [comment]
I assign a task as a mentor
as a founder, I can only comment.... 
need method to tell mentor (or assignee) task has been completed.
maybe another field. %complete
![task](https://cloud.githubusercontent.com/assets/5149368/9064638/7efbbedc-3a9b-11e5-9882-9fc073b0ca91.png)

**Comment by RignonNoel** [comment]
Le fondateur ne peut en effet que commenter les tâches pour le moment.

Cela peut être logique dans le sens que c'est au mentor de décider si cela à était fait correctement (un peu a l'image de la fermeture de nos tickets Github)

Un champ %complete peut être intéressant, il faudrais cependant voir si le monde l'utiliserait de manière correcte. Pour le moment les commentaires et les notifications font un produit minimum fonctionnel à mon avis.

**Comment by appliedrd** [comment]
ok. comment only for now.
