### ISSUE TITLE
Kanboard - Filter card "in progress", "completed", etc.

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#35]

**Comment by RignonNoel** [comment]
We have a new select as filter:
- In progress
- Completed
- All

**Comment by appliedrd** [comment]
when I create a task - the state button should be labeled `complete?`
when I edit a task the window banner should say edit task, not create task

**Comment by RignonNoel** [comment]
- The state button is now labeled complete.
- When you edit a task, the windows banner is refresh
- The submit button of the windows banner is now labeled "send"
