### ISSUE TITLE
Mise en place d'un support de couverture

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#36]
Il faudrait que nous mettions en place un support de couverture puisque la plateforme commence a prendre de la grandeur.

Peut être coveralls : https://coveralls.io/

@appliedrd : Have you a preference for the covering or can i test "coveralls" ?

**Comment by MLLadmin** [comment]
Looks cool! Go ahead.

**Comment by RignonNoel** [comment]
It's ok for the coverage: https://coveralls.io/github/MaisonLogicielLibre/TableauDeBord

We have a coverage of 79.2% for the moment.

**Comment by appliedrd** [comment]
cool tool!
