### ISSUE TITLE
IRL &  TRL summary across all companies

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#37]
we need a view of all company`s current IRL & TRL level (with last date updated for each)

**Comment by RignonNoel** [comment]
I added KPIs on the summary
It look like that for the moment (name of company hidden)

![centechtableau de bord v 1 - mozilla firefox](https://cloud.githubusercontent.com/assets/12053720/8580011/1df1d286-2586-11e5-8576-14b40e9dcc44.jpg)

**Comment by appliedrd** [comment]
good.
