### ISSUE TITLE
Add chart for time of incubation on the summary

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#47]
We need a new chart for see the time of incubation on the summary of all companies.

**Comment by RignonNoel** [comment]
We are now a chart who show the number of month spent in incubation of all company.

**Comment by RignonNoel** [comment]
![centechtableau de bord v 1 - mozilla firefox_3](https://cloud.githubusercontent.com/assets/12053720/8985594/21627c1e-36a6-11e5-81d8-e9f40c909590.jpg)

**Comment by appliedrd** [comment]
label as :  Incubation duration (months)

**Comment by RignonNoel** [comment]
Now the label is : 
- Incubation duration (months)
- Temps d'incubation (mois)
