### ISSUE TITLE
Ajout Linkedin dans Fondateurs 

### ISSUE THREAD

**Issue by gillescarrier** [CentechMTL/TableauDeBord#49]
Ajout Linkedin dans Fondateurs  

Merci,
Gilles

**Comment by RignonNoel** [comment]
Après vérification il semble que cette fonctionnalité est déjà était implémenté ici : #27 

Une nouvelle version de production devrais prendre effet dans la semaine qui vient, tu aura cette fonctionnalité à jour parmi les nouvelles.
