### ISSUE TITLE
move carte routier to canarie

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#53]

**Comment by RignonNoel** [comment]
Folks Interactive, développeur de la carte routière ne sait pas occupé de l'hébergement sur le serveur d'iWeb. C'est iWeb qui était principalement responsable de la création de l'architecture du serveur.

Il faut donc trouver quelqu'un ayant de l'expertise avec le framework meteor ou contacter iWeb.

**Comment by RignonNoel** [comment]
Migration de l'application effectué
Redirection DNS opéré
