### ISSUE TITLE
add floor plan view and navigation

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#54]
current floor plan
allow upload of an image

**Comment by appliedrd** [comment]
![web page](https://cloud.githubusercontent.com/assets/5149368/9257086/a44dd44a-41c1-11e5-9975-038ef021cb2f.jpg)

**Comment by RignonNoel** [comment]
You can now upload image on the admin pannel "home -> floorplan"
You can find a new link on the main menu to see the floorplan
