### ISSUE TITLE
new company status  'incubation (location exterior)`

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#55]
add status 'incubation (location exterior)`
label companies who are external (not on incubator map) with 'incubation (location exterior)`
add filter for companies by 'incubation (location exterior)`
add company status filter for summaries (TRL, IRL, etc...)

**Comment by RignonNoel** [comment]
You can now create a new status and move old companies in the new status.
You can already filter company by status.

I will work for the filter on the summary

**Comment by RignonNoel** [comment]
We have now a select like the select on presence
