### ISSUE TITLE
exec view

### ISSUE THREAD

**Issue by appliedrd** [CentechMTL/TableauDeBord#69]
![diapositive1](https://cloud.githubusercontent.com/assets/5149368/9581978/aa8309c6-4fd0-11e5-923c-816c68ec80fa.PNG)
![diapositive2](https://cloud.githubusercontent.com/assets/5149368/9581982/ac998168-4fd0-11e5-96af-d9fc7557fe47.PNG)
![diapositive3](https://cloud.githubusercontent.com/assets/5149368/9581984/ae44199c-4fd0-11e5-83b2-309a519bd7c6.PNG)
![diapositive4](https://cloud.githubusercontent.com/assets/5149368/9581986/afd6e5c8-4fd0-11e5-8911-e5e663f72da3.PNG)
![diapositive5](https://cloud.githubusercontent.com/assets/5149368/9581989/b5da4bea-4fd0-11e5-8474-0abb157539cd.PNG)
![diapositive6](https://cloud.githubusercontent.com/assets/5149368/9581992/baa636a2-4fd0-11e5-9519-237d14f99734.PNG)
![diapositive7](https://cloud.githubusercontent.com/assets/5149368/9581994/bd90597e-4fd0-11e5-91cc-9a4d9f6df774.PNG)

**Comment by RignonNoel** [comment]
You can now add a new "UserProfile" in the group "Executive" and see this new view.

**Comment by appliedrd** [comment]
block summary comments
