### ISSUE TITLE
Intégrer un script de génération de floor plan

### ISSUE THREAD

**Issue by RignonNoel** [CentechMTL/TableauDeBord#99]
# Model
- Supprimer le model floor plan
- Ajouter le model 'Location'
- Ajouter le model 'Salle'
- Ajouter un enum pour les types de salles
# Script
- Ajouter le script dans le projet
- Ajouter le fichier de rendu dans le projet
# Template
- Insérer le fichier de rendu dans le template
- Mettre a jour la view
# Serveur
- Mise en place d'une cron task pour refresh le floor plan

**Comment by digzol** [comment]
J'ai besoin d'importer app.company.models pour faire le foreignKey avec location mais cela me lance une erreur, quoi faire?

Erreur :

```
  File "C:\Users\username\Documents\GitHub\TableauDeBord\app\home\models.py", line 3, in <module>
    from app.company.models import Company
  File "C:\Users\username\Documents\GitHub\TableauDeBord\app\company\models.py", line 9, in <module>
    from app.founder.models import Founder
  File "C:\Users\username\Documents\GitHub\TableauDeBord\app\founder\models.py", line 6, in <module>
    from app.home.models import UserProfile,Expertise,Education
ImportError: cannot import name UserProfile
```

**Comment by RignonNoel** [comment]
Tu effectue une importation en boucle.

Tu importe company, qui importe founder, qui import userProfile qui est ton propre fichier, donc qui réimporte company, etc...

## Deux solutions:

 1 - Tu peux soit importer directement dans ton model, a l'endroit souhaité. 
 2 - company = models.ManyToManyField("company", ...) comme une chaine de caractères 

Le seconde étant plus propre!

**Comment by Digzol** [comment]
Mon script ne fonctionne pas en 2.7 puisque la method multiline_textsize n'exist pas dans cette version de PIL. Le script dépend fortement sur cette method donc je ne sais quoi faire.

**Comment by digzol** [comment]
~~Mon script dépend fortement sur une method de PIL qui n'existe pas dans la  version courante de PIL sur python 2.7.~~

EDIT : Il faudra s'assurer que la version de Pillow installé est à jour pour que mon script fonctionne correctement.

EDIT : D'autres problèmes surviennent dû au downgrade à python 2.7.
Tout le reste fonctionne correctement, il ne reste qu'à faire le downgrade des fonctions de mon script vers 2.7 puis retester le tout...
